{{- if .Values.schemaRegistry.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamhouse.fullname" . }}-schema-registry
  labels:
    {{- include "streamhouse.schemaRegistry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.schemaRegistry.service.type }}
  ports:
    - port: {{ .Values.schemaRegistry.config.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "streamhouse.schemaRegistry.selectorLabels" . | nindent 4 }}
{{- end }}
